// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// transform_list
List transform_list(int nb_proc, arma::imat table_proc_equip);
RcppExport SEXP _BloodPaTH_transform_list(SEXP nb_procSEXP, SEXP table_proc_equipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nb_proc(nb_procSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type table_proc_equip(table_proc_equipSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_list(nb_proc, table_proc_equip));
    return rcpp_result_gen;
END_RCPP
}
// BloodPaTH_model
List BloodPaTH_model(int t, int n_patients, int nb_wards, int nb_adm, arma::drowvec prev_init,std::string prev_type, arma::dmat WT_matrix, arma::dmat init_prob, arma::dcolvec adm_prob, int nb_procedures, int nb_equipments, arma::dmat PPM_matrix, Rcpp::DataFrame dist_risk, arma::imat nb_material_new, arma::imat nb_material_used, arma::imat nb_material_contaminated, int min_e_phase, int max_e_phase, float time_step, bool patient_followup, arma::imat table_proc_equip, StringVector procedure_names, StringVector equipment_names, arma::drowvec sterilization_prob, std::string eq_quantity, arma::imat refill_quantities, arma::fmat refill_freq, arma::fmat equip_bin, std::string output, float prob_screening,std::string intervention,arma::irowvec at_risk_wards,arma::frowvec threshold_reuse,std::string pathogen,int id_sim);
RcppExport SEXP _BloodPaTH_BloodPaTH_model(SEXP tSEXP, SEXP n_patientsSEXP, SEXP nb_wardsSEXP, SEXP nb_admSEXP, SEXP prev_initSEXP, SEXP prev_typeSEXP, SEXP WT_matrixSEXP, SEXP init_probSEXP, SEXP adm_probSEXP, SEXP nb_proceduresSEXP, SEXP nb_equipmentsSEXP, SEXP PPM_matrixSEXP, SEXP dist_riskSEXP, SEXP nb_material_newSEXP, SEXP nb_material_usedSEXP, SEXP nb_material_contaminatedSEXP, SEXP min_e_phaseSEXP, SEXP max_e_phaseSEXP, SEXP time_stepSEXP, SEXP patient_followupSEXP, SEXP table_proc_equipSEXP, SEXP procedure_namesSEXP, SEXP equipment_namesSEXP, SEXP sterilization_probSEXP, SEXP eq_quantitySEXP, SEXP refill_quantitiesSEXP, SEXP refill_freqSEXP, SEXP equip_binSEXP, SEXP outputSEXP, SEXP prob_screeningSEXP, SEXP interventionSEXP, SEXP at_risk_wardsSEXP,SEXP threshold_reuseSEXP,SEXP pathogenSEXP,SEXP id_simSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type n_patients(n_patientsSEXP);
    Rcpp::traits::input_parameter< int >::type nb_wards(nb_wardsSEXP);
    Rcpp::traits::input_parameter< int >::type nb_adm(nb_admSEXP);
    Rcpp::traits::input_parameter< arma::drowvec >::type prev_init(prev_initSEXP);
    Rcpp::traits::input_parameter< std::string >::type prev_type(prev_typeSEXP);
    Rcpp::traits::input_parameter< arma::dmat >::type WT_matrix(WT_matrixSEXP);
    Rcpp::traits::input_parameter< arma::dmat >::type init_prob(init_probSEXP);
    Rcpp::traits::input_parameter< arma::dcolvec >::type adm_prob(adm_probSEXP);
    Rcpp::traits::input_parameter< int >::type nb_procedures(nb_proceduresSEXP);
    Rcpp::traits::input_parameter< int >::type nb_equipments(nb_equipmentsSEXP);
    Rcpp::traits::input_parameter< arma::dmat >::type PPM_matrix(PPM_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_risk(dist_riskSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type nb_material_new(nb_material_newSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type nb_material_used(nb_material_usedSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type nb_material_contaminated(nb_material_contaminatedSEXP);
    Rcpp::traits::input_parameter< int >::type min_e_phase(min_e_phaseSEXP);
    Rcpp::traits::input_parameter< int >::type max_e_phase(max_e_phaseSEXP);
    Rcpp::traits::input_parameter< float >::type time_step(time_stepSEXP);
    Rcpp::traits::input_parameter< bool >::type patient_followup(patient_followupSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type table_proc_equip(table_proc_equipSEXP);
    Rcpp::traits::input_parameter< StringVector >::type procedure_names(procedure_namesSEXP);
    Rcpp::traits::input_parameter< StringVector >::type equipment_names(equipment_namesSEXP);
    Rcpp::traits::input_parameter< arma::drowvec >::type sterilization_prob(sterilization_probSEXP);
    Rcpp::traits::input_parameter< std::string >::type eq_quantity(eq_quantitySEXP);
    Rcpp::traits::input_parameter< arma::imat >::type refill_quantities(refill_quantitiesSEXP);
    Rcpp::traits::input_parameter< arma::fmat >::type refill_freq(refill_freqSEXP);
    Rcpp::traits::input_parameter< arma::fmat >::type equip_bin(equip_binSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    Rcpp::traits::input_parameter< float >::type prob_screening(prob_screeningSEXP);
    Rcpp::traits::input_parameter< std::string>::type intervention(interventionSEXP);
    Rcpp::traits::input_parameter< arma::irowvec >::type at_risk_wards(at_risk_wardsSEXP);
    Rcpp::traits::input_parameter< arma::frowvec >::type threshold_reuse(threshold_reuseSEXP);
    Rcpp::traits::input_parameter< std::string>::type pathogen(pathogenSEXP);
    Rcpp::traits::input_parameter< int>::type id_sim(id_simSEXP);
    rcpp_result_gen = Rcpp::wrap(BloodPaTH_model(t, n_patients, nb_wards, nb_adm, prev_init,prev_type, WT_matrix, init_prob, adm_prob, nb_procedures, nb_equipments, PPM_matrix, dist_risk, nb_material_new, nb_material_used, nb_material_contaminated, min_e_phase, max_e_phase, time_step, patient_followup, table_proc_equip, procedure_names, equipment_names, sterilization_prob, eq_quantity, refill_quantities, refill_freq, equip_bin, output,prob_screening,intervention,at_risk_wards,threshold_reuse,pathogen,id_sim));
    return rcpp_result_gen;
END_RCPP
}

// BloodPaTH_model_inter
List BloodPaTH_model_inter(int t, int n_patients, int nb_wards, int nb_adm, arma::drowvec prev_init,std::string prev_type, arma::dmat WT_matrix, arma::dmat init_prob, arma::dcolvec adm_prob, int nb_procedures, int nb_equipments, arma::dmat PPM_matrix, Rcpp::DataFrame dist_risk, arma::imat nb_material_new, arma::imat nb_material_used, arma::imat nb_material_contaminated, int min_e_phase, int max_e_phase, float time_step, bool patient_followup, arma::imat table_proc_equip, StringVector procedure_names, StringVector equipment_names, arma::drowvec sterilization_prob, std::string eq_quantity, arma::imat refill_quantities, arma::fmat refill_freq, arma::fmat equip_bin, std::string output, float prob_screening,std::string intervention,arma::irowvec at_risk_wards,arma::frowvec threshold_reuse,std::string pathogen,int id_sim);
RcppExport SEXP _BloodPaTH_BloodPaTH_model_inter(SEXP tSEXP, SEXP n_patientsSEXP, SEXP nb_wardsSEXP, SEXP nb_admSEXP, SEXP prev_initSEXP, SEXP prev_typeSEXP, SEXP WT_matrixSEXP, SEXP init_probSEXP, SEXP adm_probSEXP, SEXP nb_proceduresSEXP, SEXP nb_equipmentsSEXP, SEXP PPM_matrixSEXP, SEXP dist_riskSEXP, SEXP nb_material_newSEXP, SEXP nb_material_usedSEXP, SEXP nb_material_contaminatedSEXP, SEXP min_e_phaseSEXP, SEXP max_e_phaseSEXP, SEXP time_stepSEXP, SEXP patient_followupSEXP, SEXP table_proc_equipSEXP, SEXP procedure_namesSEXP, SEXP equipment_namesSEXP, SEXP sterilization_probSEXP, SEXP eq_quantitySEXP, SEXP refill_quantitiesSEXP, SEXP refill_freqSEXP, SEXP equip_binSEXP, SEXP outputSEXP, SEXP prob_screeningSEXP, SEXP interventionSEXP, SEXP at_risk_wardsSEXP,SEXP threshold_reuseSEXP,SEXP pathogenSEXP,SEXP id_simSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter< int >::type t(tSEXP);
  Rcpp::traits::input_parameter< int >::type n_patients(n_patientsSEXP);
  Rcpp::traits::input_parameter< int >::type nb_wards(nb_wardsSEXP);
  Rcpp::traits::input_parameter< int >::type nb_adm(nb_admSEXP);
  Rcpp::traits::input_parameter< arma::drowvec >::type prev_init(prev_initSEXP);
  Rcpp::traits::input_parameter< std::string >::type prev_type(prev_typeSEXP);
  Rcpp::traits::input_parameter< arma::dmat >::type WT_matrix(WT_matrixSEXP);
  Rcpp::traits::input_parameter< arma::dmat >::type init_prob(init_probSEXP);
  Rcpp::traits::input_parameter< arma::dcolvec >::type adm_prob(adm_probSEXP);
  Rcpp::traits::input_parameter< int >::type nb_procedures(nb_proceduresSEXP);
  Rcpp::traits::input_parameter< int >::type nb_equipments(nb_equipmentsSEXP);
  Rcpp::traits::input_parameter< arma::dmat >::type PPM_matrix(PPM_matrixSEXP);
  Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_risk(dist_riskSEXP);
  Rcpp::traits::input_parameter< arma::imat >::type nb_material_new(nb_material_newSEXP);
  Rcpp::traits::input_parameter< arma::imat >::type nb_material_used(nb_material_usedSEXP);
  Rcpp::traits::input_parameter< arma::imat >::type nb_material_contaminated(nb_material_contaminatedSEXP);
  Rcpp::traits::input_parameter< int >::type min_e_phase(min_e_phaseSEXP);
  Rcpp::traits::input_parameter< int >::type max_e_phase(max_e_phaseSEXP);
  Rcpp::traits::input_parameter< float >::type time_step(time_stepSEXP);
  Rcpp::traits::input_parameter< bool >::type patient_followup(patient_followupSEXP);
  Rcpp::traits::input_parameter< arma::imat >::type table_proc_equip(table_proc_equipSEXP);
  Rcpp::traits::input_parameter< StringVector >::type procedure_names(procedure_namesSEXP);
  Rcpp::traits::input_parameter< StringVector >::type equipment_names(equipment_namesSEXP);
  Rcpp::traits::input_parameter< arma::drowvec >::type sterilization_prob(sterilization_probSEXP);
  Rcpp::traits::input_parameter< std::string >::type eq_quantity(eq_quantitySEXP);
  Rcpp::traits::input_parameter< arma::imat >::type refill_quantities(refill_quantitiesSEXP);
  Rcpp::traits::input_parameter< arma::fmat >::type refill_freq(refill_freqSEXP);
  Rcpp::traits::input_parameter< arma::fmat >::type equip_bin(equip_binSEXP);
  Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
  Rcpp::traits::input_parameter< float >::type prob_screening(prob_screeningSEXP);
  Rcpp::traits::input_parameter< std::string>::type intervention(interventionSEXP);
  Rcpp::traits::input_parameter< arma::irowvec >::type at_risk_wards(at_risk_wardsSEXP);
  Rcpp::traits::input_parameter< arma::frowvec >::type threshold_reuse(threshold_reuseSEXP);
  Rcpp::traits::input_parameter< std::string>::type pathogen(pathogenSEXP);
  Rcpp::traits::input_parameter< int>::type id_sim(id_simSEXP);
  rcpp_result_gen = Rcpp::wrap(BloodPaTH_model_inter(t, n_patients, nb_wards, nb_adm, prev_init,prev_type, WT_matrix, init_prob, adm_prob, nb_procedures, nb_equipments, PPM_matrix, dist_risk, nb_material_new, nb_material_used, nb_material_contaminated, min_e_phase, max_e_phase, time_step, patient_followup, table_proc_equip, procedure_names, equipment_names, sterilization_prob, eq_quantity, refill_quantities, refill_freq, equip_bin, output,prob_screening,intervention,at_risk_wards,threshold_reuse,pathogen,id_sim));
  return rcpp_result_gen;
  END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BloodPaTH_transform_list", (DL_FUNC) &_BloodPaTH_transform_list, 2},
    {"_BloodPaTH_BloodPaTH_model", (DL_FUNC) &_BloodPaTH_BloodPaTH_model, 35},
    {"_BloodPaTH_BloodPaTH_model_inter", (DL_FUNC) &_BloodPaTH_BloodPaTH_model_inter, 35},
    {NULL, NULL, 0}
};

RcppExport void R_init_BloodPaTH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
