// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BloodPaTH_model
List BloodPaTH_model(float time_step, int t, std::string pathogen, int min_e_phase, int max_e_phase, int nb_patients, int nb_wards, int nb_adm, arma::dcolvec adm_prob, arma::dmat init_prob, std::string prev_type, arma::drowvec prev_init, arma::dmat WT_matrix, int nb_procedures, StringVector procedure_names, int nb_devices, StringVector device_names, arma::imat nb_devices_new, arma::imat nb_devices_used, arma::imat nb_devices_contaminated, arma::imat refill_quantities, arma::fmat refill_freq, arma::imat table_procedures_devices, arma::drowvec sterilization_prob, arma::dmat PPM_matrix, Rcpp::DataFrame dist_risk, std::string intervention, float prob_screening, arma::irowvec at_risk_wards, std::string output, int id_sim);
RcppExport SEXP _BloodPaTH_BloodPaTH_model(SEXP time_stepSEXP, SEXP tSEXP, SEXP pathogenSEXP, SEXP min_e_phaseSEXP, SEXP max_e_phaseSEXP, SEXP nb_patientsSEXP, SEXP nb_wardsSEXP, SEXP nb_admSEXP, SEXP adm_probSEXP, SEXP init_probSEXP, SEXP prev_typeSEXP, SEXP prev_initSEXP, SEXP WT_matrixSEXP, SEXP nb_proceduresSEXP, SEXP procedure_namesSEXP, SEXP nb_devicesSEXP, SEXP device_namesSEXP, SEXP nb_devices_newSEXP, SEXP nb_devices_usedSEXP, SEXP nb_devices_contaminatedSEXP, SEXP refill_quantitiesSEXP, SEXP refill_freqSEXP, SEXP table_procedures_devicesSEXP, SEXP sterilization_probSEXP, SEXP PPM_matrixSEXP, SEXP dist_riskSEXP, SEXP interventionSEXP, SEXP prob_screeningSEXP, SEXP at_risk_wardsSEXP, SEXP outputSEXP, SEXP id_simSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type time_step(time_stepSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< std::string >::type pathogen(pathogenSEXP);
    Rcpp::traits::input_parameter< int >::type min_e_phase(min_e_phaseSEXP);
    Rcpp::traits::input_parameter< int >::type max_e_phase(max_e_phaseSEXP);
    Rcpp::traits::input_parameter< int >::type nb_patients(nb_patientsSEXP);
    Rcpp::traits::input_parameter< int >::type nb_wards(nb_wardsSEXP);
    Rcpp::traits::input_parameter< int >::type nb_adm(nb_admSEXP);
    Rcpp::traits::input_parameter< arma::dcolvec >::type adm_prob(adm_probSEXP);
    Rcpp::traits::input_parameter< arma::dmat >::type init_prob(init_probSEXP);
    Rcpp::traits::input_parameter< std::string >::type prev_type(prev_typeSEXP);
    Rcpp::traits::input_parameter< arma::drowvec >::type prev_init(prev_initSEXP);
    Rcpp::traits::input_parameter< arma::dmat >::type WT_matrix(WT_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type nb_procedures(nb_proceduresSEXP);
    Rcpp::traits::input_parameter< StringVector >::type procedure_names(procedure_namesSEXP);
    Rcpp::traits::input_parameter< int >::type nb_devices(nb_devicesSEXP);
    Rcpp::traits::input_parameter< StringVector >::type device_names(device_namesSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type nb_devices_new(nb_devices_newSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type nb_devices_used(nb_devices_usedSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type nb_devices_contaminated(nb_devices_contaminatedSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type refill_quantities(refill_quantitiesSEXP);
    Rcpp::traits::input_parameter< arma::fmat >::type refill_freq(refill_freqSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type table_procedures_devices(table_procedures_devicesSEXP);
    Rcpp::traits::input_parameter< arma::drowvec >::type sterilization_prob(sterilization_probSEXP);
    Rcpp::traits::input_parameter< arma::dmat >::type PPM_matrix(PPM_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_risk(dist_riskSEXP);
    Rcpp::traits::input_parameter< std::string >::type intervention(interventionSEXP);
    Rcpp::traits::input_parameter< float >::type prob_screening(prob_screeningSEXP);
    Rcpp::traits::input_parameter< arma::irowvec >::type at_risk_wards(at_risk_wardsSEXP);
    Rcpp::traits::input_parameter< std::string >::type output(outputSEXP);
    Rcpp::traits::input_parameter< int >::type id_sim(id_simSEXP);
    rcpp_result_gen = Rcpp::wrap(BloodPaTH_model(time_step, t, pathogen, min_e_phase, max_e_phase, nb_patients, nb_wards, nb_adm, adm_prob, init_prob, prev_type, prev_init, WT_matrix, nb_procedures, procedure_names, nb_devices, device_names, nb_devices_new, nb_devices_used, nb_devices_contaminated, refill_quantities, refill_freq, table_procedures_devices, sterilization_prob, PPM_matrix, dist_risk, intervention, prob_screening, at_risk_wards, output, id_sim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BloodPaTH_BloodPaTH_model", (DL_FUNC) &_BloodPaTH_BloodPaTH_model, 31},
    {NULL, NULL, 0}
};

RcppExport void R_init_BloodPaTH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
