# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

transform_list <- function(nb_proc, table_proc_equip) {
    .Call(`_BloodPaTH_transform_list`, nb_proc, table_proc_equip)
}

BloodPaTH_model <- function(t, n_patients, nb_wards, nb_adm, prev_init, prev_type, WT_matrix, init_prob, adm_prob, nb_procedures, nb_equipments, PPM_matrix, dist_risk, nb_material_new, nb_material_used, nb_material_contaminated, min_e_phase, max_e_phase, time_step, patient_followup, table_proc_equip, procedure_names, equipment_names, sterilization_prob, eq_quantity, refill_quantities, refill_freq, equip_bin, output = "simple",prob_screening=0,intervention="none",at_risk_wards=0,threshold_reuse=0,pathogen="HCV",id_sim=1) {
    .Call(`_BloodPaTH_BloodPaTH_model`, t, n_patients, nb_wards, nb_adm, prev_init, prev_type, WT_matrix, init_prob, adm_prob, nb_procedures, nb_equipments, PPM_matrix, dist_risk, nb_material_new, nb_material_used, nb_material_contaminated, min_e_phase, max_e_phase, time_step, patient_followup, table_proc_equip, procedure_names, equipment_names, sterilization_prob, eq_quantity, refill_quantities, refill_freq, equip_bin, output,prob_screening,intervention,at_risk_wards,threshold_reuse,pathogen,id_sim)
}

BloodPaTH_model_inter <- function(t, n_patients, nb_wards, nb_adm, prev_init, prev_type, WT_matrix, init_prob, adm_prob, nb_procedures, nb_equipments, PPM_matrix, dist_risk, nb_material_new, nb_material_used, nb_material_contaminated, min_e_phase, max_e_phase, time_step, patient_followup, table_proc_equip, procedure_names, equipment_names, sterilization_prob, eq_quantity, refill_quantities, refill_freq, equip_bin, output = "simple",prob_screening=0,intervention="none",at_risk_wards=0,threshold_reuse=0,pathogen="HCV",id_sim=1) {
  .Call(`_BloodPaTH_BloodPaTH_model_inter`, t, n_patients, nb_wards, nb_adm, prev_init, prev_type, WT_matrix, init_prob, adm_prob, nb_procedures, nb_equipments, PPM_matrix, dist_risk, nb_material_new, nb_material_used, nb_material_contaminated, min_e_phase, max_e_phase, time_step, patient_followup, table_proc_equip, procedure_names, equipment_names, sterilization_prob, eq_quantity, refill_quantities, refill_freq, equip_bin, output,prob_screening,intervention,at_risk_wards,threshold_reuse,pathogen,id_sim)
}

rcpparma_hello_world <- function() {
    .Call(`_BloodPaTH_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_BloodPaTH_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_BloodPaTH_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_BloodPaTH_rcpparma_bothproducts`, x)
}

