# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BloodPaTH_model <- function(time_step, t, pathogen, min_e_phase, max_e_phase, nb_patients, nb_wards, nb_adm, adm_prob, init_prob, prev_type, prev_init, WT_matrix, nb_procedures, procedure_names, nb_devices, device_names, nb_devices_new, nb_devices_used, nb_devices_contaminated, refill_quantities, refill_freq, table_procedures_devices, sterilization_prob, PPM_matrix, dist_risk, intervention = "none", prob_screening = 0, at_risk_wards = 0L, output = "simple", id_sim = 1L) {
    .Call(`_BloodPaTH_BloodPaTH_model`, time_step, t, pathogen, min_e_phase, max_e_phase, nb_patients, nb_wards, nb_adm, adm_prob, init_prob, prev_type, prev_init, WT_matrix, nb_procedures, procedure_names, nb_devices, device_names, nb_devices_new, nb_devices_used, nb_devices_contaminated, refill_quantities, refill_freq, table_procedures_devices, sterilization_prob, PPM_matrix, dist_risk, intervention, prob_screening, at_risk_wards, output, id_sim)
}

